language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -q coveralls
  - pip install -q six
  - pip install -q mock
  - pip install -q requests
script:
  coverage run --source='wepay' --omit='*tests*' -m unittest discover -s wepay
after_success:
  coveralls
notifications:
  email:
    recipients:
      - lehins@yandex.ru
    on_success: never
    on_failure: always
