language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -q --upgrade pip
  - pip install -q coveralls
  - pip install -q six
  - pip install -q mock
  - pip install -q requests
  - pip install -q docutils
script:
  - python setup.py check --restructuredtext
  - coverage run --source='wepay' --omit='*tests*' -m unittest discover -s wepay
after_success:
  coveralls
notifications:
  email:
    recipients:x
      - lehins@yandex.ru
    on_success: never
    on_failure: always
branches:
  except:
    - /^v[0-9].[0-9].[0-9]/
