language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install coveralls
  - pip install six
  - pip install mock
  - pip install requests
script:
  coverage run --source='.' -m unittest discover -s wepay
after_success:
  coveralls
